version: '3.8'

x-defaults:
  &defaults
  init: true
  tty: true
  networks:
    - my_network

networks:
  my_network:

services:
    api:
        <<: *defaults
        ports:
          - "4000:3000"
        command: yarn workspace api dev
        environment:
          - PORT=3000
        build:
          args:
            APP: api
            START_COMMAND: dev
          context: .
          dockerfile: ./Dockerfile.dev
        volumes:
          - ./apps/api:/app/apps/api
          - /app/apps/api/node_modules
    web:
        <<: *defaults
        ports:
          - "4001:3000"
        command: yarn workspace web dev
        environment:
          - PORT=3000
        build:
          args:
            APP: web
            START_COMMAND: dev
          context: .
          dockerfile: ./Dockerfile.dev
        volumes:
          - ./apps/web:/app/apps/web
          - /app/apps/web/node_modules